
" vim-plug settings.
"""""""""""""""""""""""""""""""""""""""

" Automatic installation.
if empty(glob('~/.vim/autoload/plug.vim'))
  !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged')

Plug 'derekwyatt/vim-scala'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jieyu/ftplugin.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'vim-scripts/gtags.vim'
Plug 'hashivim/vim-hashicorp-tools'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'flazz/vim-colorschemes'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'bazelbuild/vim-ft-bzl'
Plug 'tomasr/molokai'

call plug#end()

"""""""""""""""""""""""""""""""""""""""
" Additional Vim settings.
"""""""""""""""""""""""""""""""""""""""

" General settings.
syntax on
colorscheme molokai

set ruler                       " Shows the current line number on the bar.
set number                      " Shows line numbers on the left side.
set modeline                    " Allow file-embedded modelines
set tabstop=2                   " Tab width
set softtabstop=2               " Soft tab width
set shiftwidth=2                " How much to shift text
set textwidth=72                " Default text width
set expandtab                   " Expland tab using spaces
set hlsearch                    " Highlight search terms
set cursorline                  " Highlight the current line
set showcmd                     " Show last command
set list                        " Show listchars
set listchars=tab:>.,trail:_    " Render tabs and trailing spaces
set backspace=indent,eol,start  " Makes backspace key more powerful
set completeopt=menuone         " Show insertion menu for completions
set visualbell                  " Enable vim's internal visual bell
set t_vb=                       " Set the effect of the vim visual bell to do nothing
set clipboard^=unnamed          " Allow copying between multiple vim processes
set ttyfast                     " Indicate fast terminal conn for faster redraw
set lazyredraw                  " Buffer screen updates instead of updating all the time
set autowrite                   " Automatically save before :next, :make etc.
set maxmempattern=2000          " Let plugins use more memory for things like syntax

" Clang format.
map <C-K> :pyf /usr/local/share/clang/clang-format.py<cr>
imap <C-K> <c-o>:pyf /usr/local/share/clang/clang-format.py<cr>

map :gt :Gtags
map <C-f> :FZF<CR>
map <C-o> :NERDTreeToggle<CR>

" Airline status.
let g:airline_theme = 'simple'
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'

" Workaround Nerdtree bug.
let g:NERDTreeNodeDelimiter = "\u00a0"

" Vim-go Settings.
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'
let g:go_fmt_command = "goimports"
let g:go_auto_sameids = 0
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_methods = 1
let g:go_highlight_types = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_types = 1
