"""""""""""""""""""""""""""""""""""""""
" Vundle settings.
"""""""""""""""""""""""""""""""""""""""

" Make sure that vim is not attempting to retain compatibility with
" vi, its predecessor. This is a vundle requirement. When vim attempts
" to be compatible, it disables most of the features that make it
" worth using over vi
set nocompatible

" Turn off the default filetype controls for now because the way that
" vim caches filetype rules at runtime interferes with the way that
" vundle alters the runtime environment
filetype off

" Adjust vim's runtime path to include the vundle location.
set rtp+=~/.vim/bundle/vundle

" Call the vundle initialization function.
call vundle#begin()

" Let Vundle manage itself. For GitHub repos, you specify plugins
" using the 'user/repository' format
Plugin 'gmarik/vundle'

" GNU global plugin.
Plugin 'gtags.vim'

" The NERD Tree.
Plugin 'scrooloose/nerdtree.git'

" A git wrapper.
Plugin 'tpope/vim-fugitive'

" Pig syntax highlighting.
Plugin 'motus/pig.vim'

" Go (golang) support.
Plugin 'fatih/vim-go'

" Customized file type plugin files.
Plugin 'jieyu/ftplugin.vim'

call vundle#end()

" Re-establish the filetype functionality.
filetype on             " Enables filetype detection.
filetype indent on      " Enables filetype-specific indenting.
filetype plugin on      " Enables filetype-specific plugins.

"""""""""""""""""""""""""""""""""""""""
" Additional Vim settings.
"""""""""""""""""""""""""""""""""""""""

" Display related.
syntax on               " Enables syntax highlighting.
set ruler               " Shows the current line number on the bar.
set number              " Shows line numbers on the left side.
set textwidth=70        " Maximum number of chars allowed each line.

" Tab related.
set shiftwidth=2
set softtabstop=2
set tabstop=2
set noexpandtab
